import Image from "next/image";
import { about, contact, experience, foundation, hero, toolkit } from "@/data/portfolio";
import { Navigation } from "@/components/navigation";
import { Intro, HeroDepth, HeroScrollFade, Reveal } from "@/components/motion";
import { Projects, Tags } from "@/components/projects";

function Heading({ label, children }: { label: string; children: React.ReactNode }) { return <div className="section-heading"><span className="mono section-label">{label}</span><h2>{children}</h2></div>; }

export default function Home() {
  return <><Intro/><Navigation/><main id="main" tabIndex={-1}>
    <section id="home" tabIndex={-1} className="hero section-shell" aria-labelledby="hero-title">
      <div className="hero-layout"><div className="hero-copy"><HeroScrollFade><h1 id="hero-title">WUTTIPONG<br/><span>“BEST”</span><br/>THONGMON<span className="title-period">.</span></h1><p className="hero-role mono">SOFTWARE ENGINEER</p><p className="hero-sub">Manufacturing Systems · Automation · Web Applications</p><p className="hero-statement">{hero.statement}</p><p className="availability mono"><span aria-hidden="true"/>{hero.status}</p><div className="hero-actions"><a className="button button-dark" href="#systems">View Selected Work <span aria-hidden="true">↘</span></a><a className="text-link" href={contact.links[1].url} target="_blank" rel="noopener noreferrer">LinkedIn <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a></div></HeroScrollFade></div>
      <Reveal className="hero-visual"><HeroDepth><div className="portrait-grid" aria-hidden="true"><span className="grid-label label-mes">MES</span><span className="grid-label label-sql">SQL</span><span className="grid-label label-automation">AUTOMATION</span><span className="depth-line line-h"/><span className="depth-line line-v"/></div><Image className="portrait" src="/images/best-portrait.png" alt="Wuttipong ‘Best’ Thongmon" width={540} height={631} sizes="(max-width: 700px) 90vw, 45vw" priority/></HeroDepth></Reveal></div>
      <div className="hero-bottom mono"><span>{hero.location}</span><a href="#about">SCROLL TO EXPLORE ↓</a></div>
    </section>
    <section id="about" tabIndex={-1} className="section-shell section" aria-label="Profile"><Reveal><Heading label={about.label}>{about.heading}</Heading><div className="profile-grid"><div className="profile-aside"><span className="big-number">13<span>+</span></span><span className="mono">YEARS / SOFTWARE DEVELOPMENT & SUPPORT</span><figure className="origin-image"><Image src={`/${about.image.src}`} alt="Supplied editorial illustration of technical foundations, networking, and operational systems" width={1200} height={711} sizes="(max-width: 700px) 90vw, 350px"/><figcaption>{about.image.caption}</figcaption></figure></div><div className="profile-body">{about.paragraphs.map(p => <p key={p}>{p}</p>)}<div className="profile-facts">{about.facts.slice(1).map(fact => <div key={fact.value}><h3>{fact.value}</h3><p>{fact.label}</p></div>)}</div></div></div></Reveal></section>
    <section id="experience" tabIndex={-1} className="experience-section section" aria-label="Experience"><div className="section-shell"><Heading label="02 / EXPERIENCE">A career built close<br/>to real operations.</Heading><div className="timeline">{experience.map((job, index) => <Reveal key={job.company}><article className="job"><div className="job-date"><span className="mono">{job.period}</span><span className="job-index" aria-hidden="true">0{index+1}</span></div><div className="job-body"><div className="job-heading"><div><h3>{job.role}</h3><p className="company">{job.company}</p></div><span className="mono job-location">{job.location}</span></div><p>{job.summary}</p><details open={index === 0}><summary>Selected contributions <span aria-hidden="true">+</span></summary><ul className="contributions">{job.contributions.map(c => <li key={c}>{c}</li>)}</ul></details><Tags items={job.tags}/></div></article></Reveal>)}</div></div></section>
    <section id="systems" tabIndex={-1} className="section-shell section" aria-label="Selected Systems"><Heading label="03 / SELECTED SYSTEMS">Software made for real<br/>production environments.</Heading><div className="section-intro"><p>The systems I have built and kept running in production. Practical work, grounded in real requirements.</p><span className="mono">05 SYSTEMS / 2014—2026</span></div><Projects/></section>
    <section id="toolkit" tabIndex={-1} className="toolkit-section section" aria-label="Technical toolkit"><div className="section-shell"><Heading label={toolkit.label}>{toolkit.heading}</Heading><div className="toolkit-rows">{toolkit.categories.map((category, index) => <Reveal key={category.title}><div className="toolkit-row"><span className="mono">0{index+1}</span><h3>{category.title}</h3><Tags items={category.skills}/></div></Reveal>)}</div></div></section>
    <section id="foundation" tabIndex={-1} className="section-shell section" aria-label="Education and recognition"><Heading label={foundation.label}>The foundation.<br/>And the work behind it.</Heading><div className="foundation-grid"><div><span className="mono subsection-label">EDUCATION</span>{foundation.education.map(item => <article className="education" key={item.school}><span className="mono">{item.period}</span><h3>{item.school}</h3><p>{item.degree}</p></article>)}</div><div><span className="mono subsection-label">RECOGNITION</span><article className="award"><span className="award-symbol" aria-hidden="true">✳</span><span className="mono">{foundation.recognition.date}</span><h3>{foundation.recognition.award}</h3><p>{foundation.recognition.company}</p></article><details className="certifications"><summary>Training & certifications <span aria-hidden="true">+</span></summary><ul>{foundation.certifications.map(item => <li key={item}>{item}</li>)}</ul></details></div></div></section>
    <section id="contact" tabIndex={-1} className="contact-section section" aria-label="Contact"><div className="section-shell"><span className="mono section-label">{contact.label}</span><h2>Let’s build<br/>dependable systems<span>.</span></h2><div className="contact-bottom"><p>{contact.body}</p><div className="contact-links">{contact.links.slice().reverse().map(link => <a key={link.url} href={link.url} target="_blank" rel="noopener noreferrer">{link.label} <span aria-hidden="true">↗</span><span className="sr-only"> (opens in a new tab)</span></a>)}</div></div><p className="contact-note mono">CONNECT VIA LINKEDIN / EMAIL ADDRESS KEPT PRIVATE</p></div></section>
  </main><footer className="section-shell footer"><span>{contact.footer}</span><a href="#home" className="mono">BACK TO TOP ↑</a></footer></>;
}
